[Icon Theme]
Name=Pixel Theme
Comment=A simple pixel theme
Inherits=breeze,gnome
Directories=actions/symbolic,actions/22x22,apps/scalable,devices/scalable,mimetypes/scalable,places/16x16,panel/16,places/scalable

FollowsColorScheme=true

[actions/22x22]
Size=22
Context=Actions
Type=Scalable
MinSize=16
MaxSize=48

[actions/symbolic]
Size=16
Context=Actions
Type=Scalable
MinSize=8
MaxSize=128


[apps/scalable]
Size=48
Context=Applications
Type=Scalable
MinSize=8
MaxSize=256


[devices/scalable]
Size=48
Context=Devices
Type=Scalable
MinSize=16
MaxSize=256


[mimetypes/scalable]
Size=48
Context=MimeTypes
Type=Scalable
MinSize=8
MaxSize=256


[places/16x16]
Size=16
Context=Places
Type=Fixed
#MinSize=8
#MaxSize=16

[places/scalable]
Size=48
Context=Places
Type=Scalable
MinSize=8
MaxSize=256

[panel/16]
Size=16
Context=Status
Type=Scalable
MinSize=8
MaxSize=24
